# Generated by Django 5.2.9 on 2026-01-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('soft', 'Soft')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
